"""empty message

Revision ID: 3654fc706bb3
Revises: 6b51190090a9
Create Date: 2025-02-27 20:45:41.823342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3654fc706bb3'
down_revision = '6b51190090a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Книга', schema=None) as batch_op:
        batch_op.alter_column('КодПользователя',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Книга', schema=None) as batch_op:
        batch_op.alter_column('КодПользователя',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
